# Generated by Django 3.2.9 on 2021-11-26 12:40

import consumer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('private_key', models.CharField(default=consumer.models.ConsumerSecretKeyGenerator('private_key'), max_length=64, unique=True)),
                ('public_key', models.CharField(default=consumer.models.ConsumerSecretKeyGenerator('public_key'), max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XboxLiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xbox_id', models.CharField(max_length=32, unique=True, verbose_name='xbox user id')),
                ('gamertag', models.CharField(max_length=16, verbose_name='xbox live gamertag')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xbox_live_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(default=consumer.models.TokenSecretKeyGenerator('request_token'), max_length=64, unique=True)),
                ('access_token', models.CharField(default=consumer.models.TokenSecretKeyGenerator('access_token'), max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('redirect_to', models.CharField(max_length=255)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='consumer.consumer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_id', models.CharField(max_length=64, verbose_name='microsoft account id')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
