# Generated by Django 3.2.9 on 2021-11-27 16:00

import consumer.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_delete_xboxliveaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftaccount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='private_key',
            field=models.CharField(default=consumer.models.ConsumerSecretKeyGenerator('private_key'), max_length=64, unique=True, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='public_key',
            field=models.CharField(default=consumer.models.ConsumerSecretKeyGenerator('public_key'), max_length=64, unique=True, verbose_name='Client ID'),
        )
    ]
